cd doesnt tell error

diff --git a/.github/workflows/lint_smoketest.yml b/.github/workflows/lint_smoketest.yml
--- a/.github/workflows/lint_smoketest.yml
+++ b/.github/workflows/lint_smoketest.yml
@@ -63,11 +63,15 @@ jobs:
         env:
           DJANGO_SETTINGS_MODULE: settings.cd_autotest
         run: docker-compose -f docker/docker-compose.yml up -d
-      - run: |
+      - name: Check if it stays active
+        run: |
           sleep 10
-          docker ps
+          containers=$(docker ps --format '{{.Names}}')
+          if [[ $containers != *"siddata_server_backend_1"* ]]; then
+            exit 1
+          fi
       - name: Dump docker logs on failure
-        if: failure()
+#        if: failure()
         uses: jwalton/gh-docker-logs@v1
       - name: Smoketest
         run: docker run --network container:siddata_server_backend_1 appropriate/curl -s --retry 10 --retry-connrefused http://127.0.0.1:8000/health_check/
